### ISSUE TITLE
400 Server error when importing from github

### ISSUE THREAD

**Issue by michaellee8** [CompuIves/codesandbox-client#231]
Basically I navigated to https://codesandbox.io/s/github and gave it my repo here https://github.com/michaellee8/tkpss-table-tennis-club , clicked opening sandbox and it gives me 400 internal error

**Comment by CompuIves** [comment]
Hey! Thank you very much for sending this, I just fixed another bug with it 😄 . I checked what the error could be and found that there are too many dependencies in the project (we set a limit of 20 for non-patrons).

The solution would be to move some dependencies which you don't need during in the browser bundle to `devDependencies`, so your package.json would look like this:

```json
{
  "name": "tkpss-table-tennis-club",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "firebase": "^4.5.0",
    "material-ui": "^1.0.0-beta.9",
    "material-ui-icons": "^1.0.0-beta.5",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-google-charts": "^1.5.5",
    "react-input-range": "^1.2.1",
    "react-intl": "^2.4.0",
    "react-linkify": "^0.2.1",
    "react-promise": "^2.0.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-state-promise": "^1.3.3",
    "react-visibility-sensor": "^3.11.0",
    "rechart": "^0.0.1",
    "recharts": "^1.0.0-apha.5",
    "typeface-roboto": "^0.0.35"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      "prettier --double-quote --write",
      "git add"
    ]
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.2.6",
    "@storybook/addon-links": "^3.2.6",
    "@storybook/react": "^3.2.8",
    "babel-jest": "^21.0.2",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "enzyme": "^2.9.1",
    "flow-bin": "^0.54.1",
    "flow-result-checker": "^0.2.0",
    "husky": "^0.14.3",
    "lint-staged": "^4.1.3",
    "prettier": "^1.6.1",
    "prettier-eslint": "^8.1.0",
    "regenerator-runtime": "^0.11.0",
    "react-test-renderer": "^15.6.1",
    "react-scripts": "1.0.13"
  }
}
```

Then it should work, let me know! 😄

**Comment by michaellee8** [comment]
Hey, isn't babel preset is required in dependencies

**Comment by CompuIves** [comment]
It's required for build tooling, that's why it should live in `devDependencies`. All dependencies that are sent to the browser live in `dependencies`.

**Comment by michaellee8** [comment]
I just copied and pasted what you said, but the problem is still here.
https://codesandbox.io/s/github/michaellee8/tkpss-table-tennis-club
